### ISSUE TITLE
Feature - create worksheets locally

### ISSUE THREAD

**Issue by sfc-gh-cconner** [tdambrin/sf_git#7]
This is very cool!  Any plans to be able to create a sql file and metadata locally and then push and register?

**Comment by tdambrin** [comment]
Thanks for the support!

That's actually a good idea, I'll keep this issue opened and might add the feature.
If that's something you'd want to look into the code and suggest an implementation, I'll be happy to review it.

**Comment by tdambrin** [comment]
## Feature development

### Be able to create worksheets locally

Within your worksheets folder, you could add Python/SQL files that would be uploaded to Snowflake as worksheets. Requirements as of the package behavior today are to have .worksheet_name_metadata.json files within the same folder.
Because folder architecture is replicated within the worksheet folder, Snowflake folder name can be inferred from other worksheets within the same directory if exists else derived from the folder name. 

### Tasks

- [ ] Lookup helper functions to derive metadata
- [ ]  Pattern filtering to add only *.py worksheets for example
- [ ] Implement overall procedure
- [ ] Add CLI command

### Projected release: 1.3.2
